# utils/visualizer.py
import io
import networkx as nx
import matplotlib.pyplot as plt

# Try optional Graphviz import (if not available we'll fall back)
try:
    from graphviz import Digraph
    HAVE_GRAPHVIZ = True
except Exception:
    HAVE_GRAPHVIZ = False

def _add_edges_graphviz(dot, node, tree):
    if node is None:
        return
    label = f"{node.key}\\n(h={node.height}, bf={tree.get_balance(node)})"
    dot.node(str(id(node)), label)
    if node.left:
        dot.edge(str(id(node)), str(id(node.left)))
        _add_edges_graphviz(dot, node.left, tree)
    if node.right:
        dot.edge(str(id(node)), str(id(node.right)))
        _add_edges_graphviz(dot, node.right, tree)

def draw_graphviz_avl_bytes(root, tree):
    """
    Returns PNG bytes generated by graphviz for the tree.
    Requires system Graphviz + python graphviz package.
    """
    if root is None:
        return None
    if not HAVE_GRAPHVIZ:
        return None
    dot = Digraph()
    _add_edges_graphviz(dot, root, tree)
    return dot.pipe(format='png')  # bytes

# --- fallback: networkx + matplotlib hierarchical layout
def _build_nx_tree(root, G=None):
    if G is None:
        G = nx.DiGraph()
    if root is None:
        return G
    G.add_node(root.key, height=root.height)
    if root.left:
        G.add_edge(root.key, root.left.key)
        _build_nx_tree(root.left, G)
    if root.right:
        G.add_edge(root.key, root.right.key)
        _build_nx_tree(root.right, G)
    return G

def hierarchy_pos(G, root, width=1., vert_gap=0.2, vert_loc=0, xcenter=0.5):
    """
    Compute positions for a tree for matplotlib drawing.
    G must be a networkx DiGraph representing a tree and `root` is the root node id.
    """
    def _hierarchy_pos(node, left, right, vert_loc, pos):
        pos[node] = ((left + right) / 2.0, vert_loc)
        children = list(G.successors(node))
        if len(children) == 0:
            return
        dx = (right - left) / len(children)
        nextx = left
        for child in children:
            _hierarchy_pos(child, nextx, nextx + dx, vert_loc - vert_gap, pos)
            nextx += dx

    pos = {}
    _hierarchy_pos(root, 0, width, vert_loc, pos)
    return pos

def draw_matplotlib_tree_fig(root, tree):
    """
    Returns a matplotlib.figure.Figure for the given tree (hierarchical layout).
    Use st.pyplot(fig) to show it in Streamlit.
    """
    if root is None:
        fig = plt.figure(figsize=(4, 3))
        plt.text(0.5, 0.5, "Empty tree", ha='center', va='center')
        plt.axis('off')
        return fig

    G = _build_nx_tree(root)
    pos = hierarchy_pos(G, root.key, width=1.0, vert_gap=0.15, vert_loc=0.8)
    fig, ax = plt.subplots(figsize=(8, max(4, 0.8 * (len(pos)))))
    nx.draw(G, pos=pos, with_labels=True, arrows=False, node_size=1000, ax=ax)
    # annotate nodes with (h,bf)
    for n in G.nodes:
        # find node object? the tree already holds heights; to show bf we need tree.get_balance on node
        # We annotate using the node key only for simplicity
        pass
    ax.set_axis_off()
    fig.tight_layout()
    return fig
